[[Head:Title=Login;Description=This is the page description get used to it;Keywords=home,page,setteled]]
<!-- Meta tags can be added here -->
[[css=reset,base]]
[[scripts=base]]
<!-- adhoc scripts/ css or IE fixes can be added here -->

[[EndHead]]
[[Include.PublicBaseHeader]]
<body>
	<div id="SiteWrapper">
		[[Include.PublicNav]]

		<div id="Content">
            [[Introduction]]<br />
            [[Var=WelcomMessage]]
            
            [[PageTest]]
		</div>

		<footer>
			<p>
				&copy; Copyright  by VLorun
			</p>
		</footer>
	</div>
</body>
</html>
