<header>
	<ul class="shine">
		<li class="li1"></li>
		<li class="li2"></li>
		<li class="li3"></li>
		<li class="li4">Beta 1.0</li>
		<li class="li5"></li>
		<li class="li6"></li>
	</ul>
	<img src="[[SitePath]]images/logo.png" alt="" title="" id="SiteLogo"/>
	<nav>
		<ul>
			<li><a href="[[SitePath]]public/about">about us</a></li>
			<li><a href="[[SitePath]]public/faq">faq</a></li>
			<li><a href="[[SitePath]]public/contact">contact us</a></li>
			<!--<li><a href="[[SitePath]]public/login">Login</a></li>-->
			
		</ul>
	</nav>
	[[Var=AdminMenu]]

	<div class="visual_element_balance">
		<ul class="shine">
		<li class="li1"></li>
		<li class="li2"><a href="#">login</a> <span>:</span> <a href="#">register</a></li>
		<li class="li3"></li>
		<li class="li4"></li>
		<li class="li5"></li>
	</ul>
	</div>
</header>
